//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.09 at 02:49:45 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.hermes.admin.ch/model/hermes5/v1")
package ch.admin.hermes.model.schema;
